---

version: '3.6'

services:

  dash-caddy:
    image: caddy:2
    restart: unless-stopped
    container_name: dash-caddy
    depends_on:
      - dash-server
      - dash-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

  dash-server:
    image: codingcoffee/dash-server-dev
    build:
      context: ../server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: dash-server
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=80
    volumes:
      - ../server:/app
    command: "/bin/sh -c 'npm i && npm run dev'"

  dash-client:
    image: codingcoffee/dash-client-dev
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: dash-client
    environment:
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ../client:/app
    command: "/bin/sh -c 'npm i && npm run dev'"
    environment:
      - SERVER_HOST=${SERVER_HOST?Server Host is not Set}
      - SERVER_PORT=${SERVER_PORT}
