---

version: '3.6'

services:

  dash-nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: dash-nginx
    depends_on:
      - dash-server
      - dash-client
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro

  dash-server:
    image: codingcoffee/dash-server
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dash-server
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=80

  dash-client:
    image: codingcoffee/dash-client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dash-client


